### ISSUE TITLE
How to call the airflow service?

### ISSUE THREAD

**Issue by Tscherno** [aglehmann/home_assistant_ecovent#16]
I was not able to successfully call the airflow service. Can you give me an example how to call it right?

**Comment by aglehmann** [comment]
It seems i haven't been paying enough attention to breaking changes lately. Some of the code for the "fan" component i HA has changed and the custom service does no longer receive the correct values from HA. I'll have a look and update accordingly.

Thanks for notifying me.

**Comment by gavlexx** [comment]
> It seems i haven't been paying enough attention to breaking changes lately. Some of the code for the "fan" component i HA has changed and the custom service does no longer receive the correct values from HA. I'll have a look and update accordingly.
> 
> Thanks for notifying me.

Hi. Any news for this issue? Same problem - no action for airflow service...

**Comment by gavlexx** [comment]
> I was not able to successfully call the airflow service. Can you give me an example how to call it right?

I succeeded to call service! :)
Here is my **example of working code** below:
```
action:
  - service: fan.ecovent_set_airflow
    data_template:
      entity_id: fan.livingroom_fan
      airflow: air_supply  
```   

I attemptes to pass multiple entity ids in one service call but it don't work. This code gives error while calling service:
action:
```
  - service: fan.ecovent_set_airflow
    data_template:
      entity_id: 
      - fan.livingroom_fan
      - fan.bedroom_fan
      airflow: air_supply  
```
Error is like this:
_[homeassistant.components.automation.vents_air_supply_mode_when_temp_diff_drops] vents_air_supply_mode_when_temp_diff_drops: Error executing script. Invalid data for call_service at pos 1: value should be a string for dictionary value @ data['entity_id']_
