### ISSUE TITLE
Unable to perform any actions on fan: "Unknown error"

### ISSUE THREAD

**Issue by janegilring** [aglehmann/home_assistant_ecovent#18]
I've setup the integration via HACS and the fan is visible after adding it to configuration.yaml:

```
ecovent:
  devices:
        - name: "Basement fan"
                        ip_address: 10.0.1.154
```

However, trying to perform any actions such as toggle on/off:
```
service: fan.toggle
target:
  entity_id: fan.basement_fan
```

Fails with the error "Failed to call service fan.toggle: Unknown error".

The device is a Flexit Roomie Dual Wifi which I can successfully manage via their mobile Android app. I have also successfully managed it via HA before, but due to an error regarding the manually installed custom component - it was removed a while ago.

After re-adding it via HACS, it does not work for some reason.

Any pointers on how to troubleshoot this issue?
